# Site settings
title: Campudus
email: info@campudus.com
description: > # this means to ignore newlines until "baseurl:"
  Something new...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://campudus.github.io" # the base hostname & protocol for your site
github_username:  campudus

# Build settings
encoding: "utf-8"

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

highlighter: pygments

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

markdown: kramdown

kramdown:
  input: GFM

collections:
  projects:
    output: true

defaults:
  -
    scope:
      path: de
    values:
      lang: de
  -
    scope:
      path: en
    values:
      lang: en
