# Site settings
title: Campudus Developers
email: info@campudus.com
description: Web and app development.
baseurl: /
url: "https://campudus.github.io" # the base hostname & protocol for your site

# Build settings
encoding: "utf-8"

enforce_ssl: campudus.github.io

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

# Dependencies
highlighter: true
markdown: kramdown

kramdown:
  input: GFM

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Permalinks
permalink: pretty
#relative_permalinks: false

# Path / type specific variables
defaults:
  -
    values:
      order: zzzz
  -
    scope:
      path: de
    values:
      lang: de
  -
    scope:
      path: "en/products"
    values:
      layout: "product"
  -
    scope:
      path: "en/projects"
    values:
      layout: "project"
  -
    scope:
      path: "de/produkte"
    values:
      layout: "product"
      idPrefix: "products"
  -
    scope:
      path: "de/projekte"
    values:
      layout: "project"
      idPrefix: "projects"
  -
    scope:
      path: en
    values:
      lang: en
  -
    scope:
      type: posts
    values:
      layout: post
