# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: false

# Site settings
title:            Campudus Developers
email:            info@campudus.com
description: > # Web and app development.
baseurl: / # the subpath of your site, e.g. /blog/
url:              "http://campudus.com" # the base hostname & protocol for your site
github_username:  campudus
paginate:         5

# Build settings
encoding: "utf-8"

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

markdown: kramdown

kramdown:
  input: GFM


collections:
  projects:
    permalink: /projects/:path/
    output: true

defaults:
  -
    scope:
      path: "/projects"
      type: "projects"
    values:
      layout: project