# Site settings
title: Campudus Developers
email: info@campudus.com
description: Web and app development.
baseurl: /
url: "https://campudus.github.io" # the base hostname & protocol for your site

# Build settings
encoding: "utf-8"

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

# Dependencies
highlighter: true
markdown: kramdown

kramdown:
  input: GFM

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Permalinks
permalink: pretty
#relative_permalinks: false

# Path / type specific variables
defaults:
  -
    scope:
      path: de
    values:
      lang: de
  -
    scope:
      path: "de/produkte"
    values:
      idPrefix: "products"
  -
    scope:
      path: "de/projekte"
    values:
      idPrefix: "projects"
  -
    scope:
      path: en
    values:
      lang: en
  -
    scope:
      type: posts
    values:
      layout: post
